name: Send to Discord

on:
  push:
    branches: master
  # schedule:
  #  - cron: '* */6 * * *'

jobs:
  send-to-discord-pipe:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'node'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install packages
        run: npm install

      - name: Run script
        run: node newPosts.js
